// @generated
// This file is @generated by prost-build.
/// One Frame = one transport frame (WS binary message / boundary frame).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Frame {
    /// 0 = connection-level
    #[prost(uint64, tag = "1")]
    pub stream_id: u64,
    /// session layer; ignored in phase 1
    #[prost(uint64, tag = "2")]
    pub seq: u64,
    #[prost(oneof = "frame::Kind", tags = "3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14")]
    pub kind: ::core::option::Option<frame::Kind>,
}
/// Nested message and enum types in `Frame`.
pub mod frame {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "3")]
        Open(super::Open),
        #[prost(message, tag = "4")]
        Headers(super::Headers),
        #[prost(message, tag = "5")]
        Message(super::Message),
        #[prost(message, tag = "6")]
        HalfClose(super::HalfClose),
        #[prost(message, tag = "7")]
        Status(super::Status),
        #[prost(message, tag = "8")]
        Cancel(super::Cancel),
        #[prost(message, tag = "9")]
        Ping(super::Ping),
        #[prost(message, tag = "10")]
        Pong(super::Pong),
        #[prost(message, tag = "11")]
        WindowUpdate(super::WindowUpdate),
        #[prost(message, tag = "12")]
        GoAway(super::GoAway),
        #[prost(message, tag = "13")]
        Hello(super::Hello),
        #[prost(message, tag = "14")]
        Ack(super::Ack),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MetadataEntry {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(oneof = "metadata_entry::Value", tags = "2, 3")]
    pub value: ::core::option::Option<metadata_entry::Value>,
}
/// Nested message and enum types in `MetadataEntry`.
pub mod metadata_entry {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag = "2")]
        Ascii(::prost::alloc::string::String),
        /// keys with the "-bin" suffix
        #[prost(bytes, tag = "3")]
        Bin(::prost::bytes::Bytes),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Metadata {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<MetadataEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Open {
    /// "/pkg.Service/Method"
    #[prost(string, tag = "1")]
    pub method: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<Metadata>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Headers {
    #[prost(message, optional, tag = "1")]
    pub metadata: ::core::option::Option<Metadata>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Message {
    #[prost(bytes = "bytes", tag = "1")]
    pub payload: ::prost::bytes::Bytes,
    /// reserved; phase 1 does not compress
    #[prost(bool, tag = "2")]
    pub compressed: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HalfClose {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Status {
    /// gRPC status code
    #[prost(uint32, tag = "1")]
    pub code: u32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub trailers: ::core::option::Option<Metadata>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Cancel {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ping {
    #[prost(uint64, tag = "1")]
    pub opaque: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Pong {
    #[prost(uint64, tag = "1")]
    pub opaque: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WindowUpdate {
    /// stream_id comes from Frame; 0 = connection window
    #[prost(uint32, tag = "1")]
    pub increment: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GoAway {
    #[prost(uint64, tag = "1")]
    pub last_stream_id: u64,
    /// GoAwayCode
    #[prost(uint32, tag = "2")]
    pub code: u32,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Hello {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(uint32, tag = "2")]
    pub initial_stream_window: u32,
    #[prost(uint32, tag = "3")]
    pub initial_connection_window: u32,
    /// session layer (spec §8):
    #[prost(bytes = "bytes", tag = "4")]
    pub session_id: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "5")]
    pub resume_token: ::prost::bytes::Bytes,
    #[prost(uint64, tag = "6")]
    pub last_recv_seq: u64,
    /// Server response: resume rejected (unknown session / token / TTL).
    /// The client must consider the session dead.
    #[prost(bool, tag = "7")]
    pub resume_rejected: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ack {
    #[prost(uint64, tag = "1")]
    pub last_seq: u64,
}
// @@protoc_insertion_point(module)
