//! slozhn-frame — envelope protocol and stream-multiplexing state machine.
//! Core of the slozhn stack (spec: `docs/superpowers/specs/2026-07-08`).
//!
//! Transport-agnostic: [`connection::bind`] accepts any
//! `Stream<Item = Frame> + Sink<Frame>`. The driver is a future spawned by
//! the caller (`tokio::spawn` on native, `spawn_local` in wasm).
//!
//! Stream semantics = gRPC: `Open → [Message/HalfClose]* → Status`,
//! explicit `Cancel`, per-stream + connection flow control (h2 model,
//! messages are never split — the window may go negative by one message),
//! `GoAway` for graceful shutdown. Frame types come from the `slozhn-proto`
//! crate (generated by easyp from `protocols/slozhn/v1/frame.proto`).

pub mod codec;
pub mod connection;
pub mod error;
pub mod ext;
pub mod flow;
pub mod http;
pub mod ids;
pub mod loopback;
pub mod proto;
pub mod stream;
pub mod transport;

pub use connection::{
    Config, Connection, ConnectionDriver, Incoming, RecvHalf, SendHalf, WeakConnection, bind,
    bind_pre_negotiated,
};
pub use error::{ConnError, GoAwayCode, OpenError, ProtocolError, StreamError, TransportClosed};
pub use ids::Side;
pub use stream::StreamEvent;

pub const PROTOCOL_VERSION: u32 = 1;
pub const DEFAULT_WINDOW: u32 = 65_536;
pub const MAX_WINDOW: i64 = (1 << 31) - 1;
pub const MAX_MESSAGE_SIZE: usize = 4 * 1024 * 1024;
