// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Msg {
    #[prost(bytes = "bytes", tag = "1")]
    pub payload: ::prost::bytes::Bytes,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Count {
    #[prost(uint32, tag = "1")]
    pub n: u32,
}
include!("testing.v1.tonic.rs");
// @@protoc_insertion_point(module)